### ISSUE TITLE
Latest commit failed to build with boost 1.72.0

### ISSUE THREAD

**Issue by huyz-git** [thezbyg/gpick#182]
When build latest commit on `Archlinux` with latest `boost 1.72.0`, I got the following error:
```
In file included from /usr/include/boost/endian/detail/endian_reverse.hpp:13,
                 from /usr/include/boost/endian/conversion.hpp:11,
                 from /tmp/gpick/source/dynv/Types.cpp:23:
/usr/include/boost/endian/conversion.hpp: In instantiation of 'constexpr EndianReversible boost::endian::little_to_native(EndianReversible) [with EndianReversible = float]':
/tmp/gpick/source/dynv/Types.cpp:183:46:   required from here
/usr/include/boost/endian/conversion.hpp:191:5: error: static assertion failed: detail::is_endian_reversible<EndianReversible>::value
  191 |     BOOST_STATIC_ASSERT( detail::is_endian_reversible<EndianReversible>::value );
      |     ^~~~~~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/gpick-dynv.dir/build.make:109: CMakeFiles/gpick-dynv.dir/source/dynv/Types.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:195: CMakeFiles/gpick-dynv.dir/all] Error 2
make: *** [Makefile:150: all] Error 2
```
Commit https://github.com/thezbyg/gpick/commit/5e2a63b7d0e9069f1bd485d2a112c1690575e454 can build successful.
And starting from the next commit https://github.com/thezbyg/gpick/commit/c9091843c956dc7ef23d83256ba0a97b223a090f I can't build, and got this error.
